= Polyglot Programming with C-Family Programming Languages
Karl Giesing <khzmusik@hotmail.com>

== About the Book

This repo is going to hold a book that I am writing.
As you probably have guessed, the working title is "Polyglot Programming with C-Family Programming Languages."
(Let me know if you have a better one.)

My intent is that this book will serve as:

* An introduction to programming, for relative beginners, in languages that share their basic syntax with C.

* A compare-and-contrast between how these languages work, for those who are familiar with one language (e.g. JavaScript) but not the others.

* An introduction to the different programming paradigms and semantics that these languages support, e.g. procedural vs. object-oriented vs. functional.

* A way to broaden my own knowledge.

I will be releasing the book under an open license.
For the moment, the license I have chosen is the
http://creativecommons.org/licenses/by-nc/4.0/[Creative Commons Attribution-NonCommercial 4.0 International License].
This way, it can be extensively quoted, remixed, and built upon by others, so long as they do not sell it.
If the book turns out to be good enough, I'm hoping that it could also serve as teaching materials or a textbook for lower-level computer science courses.

The main reason that I am writing this book is because I would love to have learned to program from a book like this.
It would have saved me a lot of time when moving from one language to another.
It also would have made it *much* easier to learn programming languages like Scheme, where both the syntax *and* semantics are fundamentally different than, say, C or Java.
As far as I know, no book of this nature currently exists.

== Using the Repo
The book is written in AsciiDoc syntax.
This will make it easier to read here on GitHub, and the AsciiDoc syntax can easily be converted into other formats as needed.

The format and structure of the book follows the
http://asciidoctor.org/docs/asciidoc-recommended-practices/[AsciiDoc Recommended Practices]
from http://asciidoctor.org/[Asciidoctor].
Preference is given to those parts of the AsciiDoc syntax that are supported by GitHub, so that it can be read in the repo itself.

=== File Structure
The AsciiDoc files for the book itself are in a directory called `src`.
The `src` folder contains several sub-folders, which represent the different parts of the book's structure.
Each of those sub-folders may also have sub-folders, to organize the book better (into e.g. sections and chapters).
The directories are not prefixed by numbers; I believe this makes it more clear that the book can be "remixed" at will.

Within each directory is a file called `index.adoc`.
The purpose of this file is to import all the other AsciiDoc documents that make up that part of the book.
If you would like to remix the book, the easiest way is to fork the repo, and simply change the `index.adoc` files.
You can include the files in any order you prefer, or not include specific files at all.

NOTE: There may be some files in the `src` folder that are not included by any `index.adoc` file.
    These files should be regarded as working files that are not yet ready to be included in the book itself.

=== Branch Structure

This repository uses the GitFlow branching model.

For those unfamiliar with this model, here is a brief overview:

* The `master` branch is reserved for released versions.
  Since this is a book, a "released version" will be a published edition.
* The most up-to-date working branch is named `develop`.
  If you want to read the book as it is being written, this is the branch to view.
* New features are done on feature branches, named `feature/[feature-to-implement]`.
  Feature branches are branched off of, and merged to, the `develop` branch (not `master`).
  In this case, a "feature" is text to be written or changed in the book.
* Release branches are dedicated to a single release version, and created _just prior_ to that release.
  They are named `release/[upcoming-version]`.
  They are branched off of `develop` (which is now used for the next version).
  When that version is released, the branch is merged into both `develop` and `master`,
  and `master` is tagged with that version.
  In software development, the version string is usually a semantic version (major.minor.patch);
  but since this is a book, the "version" will be an edition, in the form "Nth_ed".
* Hotfixes (or maintenance fixes) are created when there is an issue with the released version,
  and it cannot wait until the next version to be fixed.
  They are named `hotfix/[fix-to-implement]`, are branched off of `master`,
  and merged into both `master` and `develop` when finished.
  Since this is a book, a hotfix will result in a revision to that edition.

In addition, I'm using a convention that seems to be very common,
especially to people like me who use Attlassian Jira for a living:
I am naming all branches after issues.

The branch name will start with the issue number, followed by a summary of the issue title,
with spaces separated by hyphens (similar to how blog titles are translated to URLs).
So, if an issue on GitHub is issue number 42, with the title "Find: meaning of life, the universe, and everything",
the branch would be named something like `feature/42-find-life-universe-everything`.

Further reading:

* https://nvie.com/posts/a-successful-git-branching-model/[A successful Git branching model] by Vincent Driessen
* https://datasift.github.io/gitflow/IntroducingGitFlow.html[Introducing GitFlow] at DataSift
* https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow[Gitflow Workflow] at Atlassian


== Content changes
If you have found a mistake in any part of the book, I would appreciated it if you raised an issue in the GitHub issue tracker.
Grammar Nazis are welcome.

If it's a conceptual issue (e.g. a bad definition of "function"), then I would *really* appreciate a cite of some trustworthy source.
This way, I know exactly why I'm wrong, and what changes I can make to be correct.
Sources are not required to be accessible online, though it is more convenient for me if they are.

I am not looking for help in writing the book itself.
But on the off chance that you are interested, you are more than welcome to either make your own branch and issue a pull request, or simply fork the repo.
I believe the former is better for the book, but that's up to you to decide.
