== Values and References
** Pass by value: argument's value is copied to parameter
***  Good, because argument won't be changed if parameter is altered inside
        function
***  Bad, because value must be copied in memory (e.g. big obj.)
** Pass by reference: argument's memory location copied to parameter
***  Good, because you only need to copy a memory location (not entire obj.)
***  Bad, because argument is shared (mutable)
**** change to param will also change arg - ignores scope
          semantics, automatically makes fn. an impure fn.
***  Some languages (Clu) refer to this as "call-by-sharing;"
        but the term is not widely used
*** Only a memory location can be passed by reference
**** No literals, e.g. `5` or `"Hello, world!"`
**** No results of expressions, e.g. `5 + 7` or `x - 1`
** C/C++ reference semantics
***  Start with these, because they are the basis for other lang's, and the
        explicit differences will make understanding other lang's easier
***  C/C++: Pointers
****  When passing by pointer, the pointer itself is passed by value;
          that is, the memory address is copied
****  Pass a value type by pointer:
[source,{cpp}]
----
void f(int* param); // function prototype
// in caller:
int arg = 5;
f(&arg);            // note address-of operator
f(&5);              // won't compile - must be addr of lvalue
----
****  Arrays are just "syntactic sugar" for pointer:
[source,{cpp}]
----
// Function declaration (prototype):
int f(int[] arr);    // Formal parameter is array of int's
int f(int* arr);     // Identical behavior!
// in caller:
int result;
int[] arr = {5, 6, 7. 8, 9};
result = f(arr);     // Note: no address-of operator
result = f(&arr[0]); // Identical behavior!
----
****  The C/C++ term for this is a "simulated reference"
            Semantically identical to pointer, but does not use pointer syntax
***  C++: References
****  When passing by reference, the parameter becomes an alias of the argument value
****  Pass a value type by reference:
[source,{cpp}]
----
void f(int& x); // function prototype
// in caller:
int arg = 5;
f(arg);         // no address-of operator!
f(5);           // won't compile - reference must be mutable
----

***  References vs. pointers: semantically different
[source,{cpp}]
----
// Pass by pointer function definition
void passByPtr(int* p)
{
  int x = 5;
  p = &x;
}
// Pass by reference function definition
void passByRef(int& r)
{
  int x = 5;
  r = x;
}
// In caller:
int a = 3;
passByPtr(&a);  // a has value 3; its mem loc was passed by value
passByRef(a);   // a has value 5!
// What about using a pointer?
a = 3;        // reset back to 3
int* b = &a;
passByPtr(b);   // a has value 3; b was passed by value
passByRef(*b);  // a has value 5!
----
***  const params: making shared arguments immutable
****  Pointers:
[source,{cpp}]
----
void f1(const int* param);       // *param is const; no assignment
void f2(int* const param);       // param is const; *param is not!
void f3(const int* const param); // param and *param are const
// in caller:
int arg = 5;
f1(&arg); // arg can't change (param can be re-referenced)
f2(&arg); // arg can change! (param can't be re-referenced)
f3(&arg); // arg can't change value (param can't be re-referenced)
----
****  References:
[source,{cpp}]
----
int f(const int& param); // param is completely immutable
// in caller:
int arg = 5;
f(arg); // arg can't change
f(5);   // this will compile! arg is reference to immutable rvalue
----
** Other C-style languages:
*** Value types are *always* passed by value
*** Reference types are passed by reference, but a "reference" is
        semantically identical to a pointer - i.e. they are what C/C++ calls
        "pass by simulated reference"
*** C has no references; use pointers
*** In PHP, references are aliases to symbol table entries:
          http://php.net/manual/en/language.references.php
        HOWEVER, they behave semantically like pass-by-pointer
*** Java has `final` instead of `const`, and it is only equivalent to `T* const param`;
    that is, it can't be re-assigned, but can be changed.
    (Only for references.)
