= Recursion

== Mutual Recursion
* Driver: function that acts as an entry point for a recursive function
** Usually, calls recursive function with base case as argument

== Base Cases

== Tail Recursion
* Very last expression is recursive function call
* Unnecessary to keep context of calling function
* Most compilers can optimize tail recursion, so function context is re-used on stack
* Tail recursion is equivalent to iteration - and vice versa

== Midpoint Recursion
* Any type of recursion other than tail recursion
* Because operations occur after recursive call, it is necessary to keep function context on stack

=== Example: Fibonacci numbers
Let's say you have been taked with writing a function that can find the n^th Fibonacci number.
The function's signature will be `int fib(int n)`.
Here, `n` is the position of the Fibonacci number in the Fibonacci sequence.
The function's return value is the actual value of the Fibonacci number.

Recall that a Fibonacci number is defines this way:
* The value of the first Fibonacci number is 1.
* The value of the second Fibonacci number is also 1.
* For all subsequent Fibonacci numbers, its value is the sum of the previous two values.

So, to find the third Fibonacci number, add the second Fibonacci number (1) and the first Fibonacci number (also 1) to get 2.
For the fourth Fibonacci number, add the third Fibonacci number (2) and the second Fibonacci number (1) to get 3.
And so on.

This lends itself to recursion in a fairly obvious way:
* `n == 1` is a base case, and it returns `1`.
* `n == 2` is also a base case, and it also returns `1`.
* All other values of `n` should return `fib(n - 1) + fib(n - 2)`.

Here is the implementation of the `fib` function in C:
[source, c]
-----
int fib(int n)
{
    if (n == 1)
        return 1;
    if (n == 2)
        return 1;
    return fib(n - 1) + fib(n - 2);
}
-----
(The two `if` statements could also be combined into one, by using the `||` operator.
I'm keeping the two base cases separate for clarity.)

==== Why This Is Bad
Consider the case where you calculate `fib(5)`.
Here are the recursive calls to `fib` in order:
* `fib(5)` calls `fib(4)`.
** `fib(4)` calls `fib(3)`
*** `fib(3)` calls `fib(2)`.
**** `fib(2)` returns 1.
*** `fib(3)` calls `fib(1)`.
**** `fib(1)` returns 1.
*** `fib(3)` finishes recursing, and returns 2. x
** `fib(4)` next calls `fib(2)`.
*** `fib(2)` returns 1.
** `fib(4)` finishes recursing, and returns 3. x
* `fib(5)` calls `fib(3)`.
** `fib(3)` calls `fib(2)`.
*** `fib(2)` returns 1.
** `fib(3)` calls `fib(1)`.
*** `fib(1)` returns 1.
** `fib(3)` finishes recursing, and returns 2. x
* `fib(5)` finishes recursing, and returns 5. x

This is a huge amount of recursive calls.
Counting them all up:
* `fib(1)` gets recursively called 2 times.
* `fib(2)` gets recursively called 3 times.
* `fib(3)` gets recursively called 2 times.
* `fib(4)` gets recursively called 1 time.

Now consider what would happen if you called, say, `fib(100)`.
The number of recursive calls would result in out-of memory errors.
Even if you did somehow have enough memory for these calls, processing them all would take an unacceptably long time.

All of the repeated calls are completely unnecessary, because the `fib` function is _deterministic._
Calling `fib(5)` will always return the same value.

It would be much better if we could simply keep track of the results of previous calls.
That way, we don't have to make the recursive calls again.

The name for this solution is _memoization._

==== Memoization
Memoization is the computer optimization technique of storing calculated results in some data structure, so they can be looked up rather than re-calculated.

While it is most commonly used to prevent repeated recursive calls, this is certainly not its only use.
In fact, it can be used anywhere a calculation could be "expensive" in any way.
"Expensive," in this case, can be defined as "using more resources than the memoization implementation itself."

In the case of our Fibonacci function, we can use a simple array to store the results.
Here, `n` would be the index of the array, and the result would be the value stored in the array element.
The expense of this memoization would primarily be the memory needed to hold the array.
But consider the size of the function stack that is created each time a recursive function is called.
Even a very large array would still be an improvement.

Let's implement our solution, as above, in the C language.
To keep things simple, we'll create a global array to hold the Fibonacci numbers, called `fib_nums`.
So that we don't have to bother with memory allocation issues, we'll declare it as a static array with 100 elements.

We'll need some special value to signify that the Fibonacci number hasn't been stored in the array yet.
Because a Fibonacci number cannot be negative, let's choose the value of `-1`.

Here is the code that will create the array:
[source, c]
-----
int fib_array[100];
// Initialize each value to -1
int i;
for (i = 0; i < 100; i++)
{
    fib_array[i] = -1;
}
-----

Our `fib` function can now be modified as follows:
[source, c]
-----
int fib(int n)
{
    int result = fib_array[n];
    if (result == -1)
    {
        /* Base cases are the same */
        if (n == 1)
        {
            result = 1;
        }
        else if (n == 2)
        {
            result = 1;
        }
        else
        {
            /* Not yet calculated; recursively calculate and memoize */
            result = fib(n - 1) + fib(n - 2);
        }

        fib_array[n] = result;
    }

    return result;
}
-----
This is a simple implementation, meant to be instructive.
There is lots of room for improvement; there is no bounds checking, the array could be resized as necessary, etc.
Most languages have array-like data structures that do this for you, but each language is different.
(Examples: the C++ standard library's `vector` type, the Java `ArrayList` type, or the C# `List` type.)

I'll leave these improvements as an exercise for the reader.
